// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VotacionDAL;

#nullable disable

namespace VotacionDAL.Migrations
{
    [DbContext(typeof(VotacionContext))]
    [Migration("20250721175751_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VotacionObjetos.Models.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("VotacionObjetos.Models.Votante", b =>
                {
                    b.Property<string>("Cedula")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SiVoto")
                        .HasColumnType("bit");

                    b.HasKey("Cedula");

                    b.ToTable("Votantes");
                });

            modelBuilder.Entity("VotacionObjetos.Models.Voto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CedulaVotante")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CedulaVotante")
                        .IsUnique();

                    b.HasIndex("PartidoId");

                    b.ToTable("Votos");
                });

            modelBuilder.Entity("VotacionObjetos.Models.Voto", b =>
                {
                    b.HasOne("VotacionObjetos.Models.Votante", "Votante")
                        .WithOne("Voto")
                        .HasForeignKey("VotacionObjetos.Models.Voto", "CedulaVotante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VotacionObjetos.Models.Partido", "Partido")
                        .WithMany("Votos")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Partido");

                    b.Navigation("Votante");
                });

            modelBuilder.Entity("VotacionObjetos.Models.Partido", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("VotacionObjetos.Models.Votante", b =>
                {
                    b.Navigation("Voto")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
